spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:mysql://localhost:3306/petcareauthdb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  flyway:
    locations: classpath:db/migration
    enabled: true

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8084

logging:
  level:
    com.roze.auth_service.service: DEBUG

