spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:mysql://localhost:3306/petcareauthdb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  flyway:
    locations: classpath:db/migration
    enabled: true

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  cache:
    redis:
      time-to-live: "2h"
  redis:
    host: ${SPRING_REDIS_HOST:redis}
    port: ${SPRING_REDIS_PORT:6379}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      group-id: auth-service-group
      auto-offset-reset: earliest

server:
  port: 8084

logging:
  level:
    com.roze.auth_service.service: DEBUG