version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      default:
        ipv4_address: 172.18.0.20

  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE: 'false'
    depends_on:
      - zookeeper
    networks:
      default:
        ipv4_address: 172.18.0.21

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      default:
        ipv4_address: 172.18.0.22

  service-registry:
    build:
      context: ./service-registry
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    networks:
      default:
        ipv4_address: 172.18.0.10

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - service-registry
    environment:
      - eureka.client.service-url.defaultZone=http://service-registry:8761/eureka
    networks:
      default:
        ipv4_address: 172.18.0.2
    extra_hosts:
      - "auth-service:172.18.0.3"
      - "user-service:172.18.0.4"
      - "appointment-service:172.18.0.5"
      - "notification-service:172.18.0.6"
      - "auditing-service:172.18.0.7"

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    depends_on:
      - service-registry
      - auth-db
      - redis
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://auth-db:3306/petcareauthdb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - eureka.client.service-url.defaultZone=http://service-registry:8761/eureka
      - SPRING_REDIS_HOST=172.18.0.22
      - SPRING_REDIS_PORT=6379
    networks:
      default:
        ipv4_address: 172.18.0.3

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - service-registry
      - user-db
      - redis
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://user-db:3306/petcareuserdb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - eureka.client.service-url.defaultZone=http://service-registry:8761/eureka
      - SPRING_REDIS_HOST=172.18.0.22
      - SPRING_REDIS_PORT=6379
    networks:
      default:
        ipv4_address: 172.18.0.4

  appointment-service:
    build:
      context: ./appointment-service
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - service-registry
      - appointment-db
      - kafka
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://appointment-db:3306/petcareappointmentdb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - eureka.client.service-url.defaultZone=http://service-registry:8761/eureka
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    networks:
      default:
        ipv4_address: 172.18.0.5

  notification-service:
    build:
      context: ./notification-service
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    depends_on:
      - service-registry
      - kafka
    environment:
      - eureka.client.service-url.defaultZone=http://service-registry:8761/eureka
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    networks:
      default:
        ipv4_address: 172.18.0.6

  auditing-service:
    build:
      context: ./auditing-service
      dockerfile: Dockerfile
    ports:
      - "8085:8085"
    depends_on:
      - service-registry
      - audit-db
      - kafka
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://audit-db:3306/petcareauditdb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - eureka.client.service-url.defaultZone=http://service-registry:8761/eureka
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    networks:
      default:
        ipv4_address: 172.18.0.7

  auth-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: petcareauthdb
    ports:
      - "3306:3306"
    networks:
      default:
        ipv4_address: 172.18.0.8

  user-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: petcareuserdb
    ports:
      - "3307:3306"
    networks:
      default:
        ipv4_address: 172.18.0.9

  appointment-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: petcareappointmentdb
    ports:
      - "3308:3306"
    networks:
      default:
        ipv4_address: 172.18.0.11

  audit-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: petcareauditdb
    ports:
      - "3309:3306"
    networks:
      default:
        ipv4_address: 172.18.0.12

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/24
