spring:
  application:
    name: api-gateway
  cloud:
    gateway:
     routes:
       - id: user-service
         uri: http://localhost:8081
         predicates:
           - Path=/api/v1/users/**

       - id: appointment-service
         uri: http://localhost:8082
         predicates:
           - Path=/api/v1/appointments/**

       - id: auth-service
         uri: http://localhost:8084
         predicates:
           - Path=/api/v1/auth/**

server:
  port: 8080
