spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://user-service:8081
          predicates:
            - Path=/api/v1/users/**
          filters:
            - AuthenticationFilter

        - id: appointment-service
          uri: http://appointment-service:8082
          predicates:
            - Path=/api/v1/appointments/**
          filters:
            - AuthenticationFilter

        - id: auth-service
          uri: http://auth-service:8084
          predicates:
            - Path=/api/v1/auth/**

server:
  port: 8080

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://service-registry:8761/eureka
#    fetch-registry: true
#    register-with-eureka: true
#  instance:
#    prefer-ip-address: true
