spring:
  application:
    name: auditing-service

  datasource:
    url: jdbc:mysql://localhost:3306/petcareauditdb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  flyway:
    locations: classpath:db/migration
    enabled: true

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update


  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: audit-service-group
      auto-offset-reset: earliest

server:
  port: 8085