spring:
  application:
    name: user-service

  datasource:
    url: jdbc:mysql://localhost:3306/petcareuserdb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    locations: classpath:db/migration
    enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  cache:
    redis:
      time-to-live: "1h"
  redis:
    host: ${SPRING_REDIS_HOST:redis}
    port: ${SPRING_REDIS_PORT:6379}


server:
  port: 8081

