spring:
  application:
    name: appointment-service

  datasource:
    url: jdbc:mysql://localhost:3306/petcareappointmentdb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  flyway:
    locations: classpath:db/migration
    enabled: true

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}

  resilience4j.retry:
    instances:
      userServiceRetry:
        max-attempts: 3
        wait-duration: 10s
        ignore-exceptions:
          - com.roze.appointment_service.exception.NotFoundException
        retry-exceptions:
          - feign.RetryableException
          - java.net.UnknownHostException

server:
  port: 8082